sonar.projectKey=cipher-forge
sonar.projectName=Cipher Forge - Gestion Fotografias
sonar.projectVersion=1.0
sonar.sources=backend,frontend-cliente,frontend-fotografo
sonar.sourceEncoding=UTF-8
sonar.exclusions=backend/backups/**,backend/uploads/**,**/.git/**